require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataProcessingTypesController do

  # This should return the minimal set of attributes required to create a valid
  # DataProcessingType. As you add validations to DataProcessingType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataProcessingTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all data_processing_types as @data_processing_types" do
      data_processing_type = DataProcessingType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:data_processing_types).should eq([data_processing_type])
    end
  end

  describe "GET show" do
    it "assigns the requested data_processing_type as @data_processing_type" do
      data_processing_type = DataProcessingType.create! valid_attributes
      get :show, {:id => data_processing_type.to_param}, valid_session
      assigns(:data_processing_type).should eq(data_processing_type)
    end
  end

  describe "GET new" do
    it "assigns a new data_processing_type as @data_processing_type" do
      get :new, {}, valid_session
      assigns(:data_processing_type).should be_a_new(DataProcessingType)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_processing_type as @data_processing_type" do
      data_processing_type = DataProcessingType.create! valid_attributes
      get :edit, {:id => data_processing_type.to_param}, valid_session
      assigns(:data_processing_type).should eq(data_processing_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataProcessingType" do
        expect {
          post :create, {:data_processing_type => valid_attributes}, valid_session
        }.to change(DataProcessingType, :count).by(1)
      end

      it "assigns a newly created data_processing_type as @data_processing_type" do
        post :create, {:data_processing_type => valid_attributes}, valid_session
        assigns(:data_processing_type).should be_a(DataProcessingType)
        assigns(:data_processing_type).should be_persisted
      end

      it "redirects to the created data_processing_type" do
        post :create, {:data_processing_type => valid_attributes}, valid_session
        response.should redirect_to(DataProcessingType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_processing_type as @data_processing_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessingType.any_instance.stub(:save).and_return(false)
        post :create, {:data_processing_type => { "name" => "invalid value" }}, valid_session
        assigns(:data_processing_type).should be_a_new(DataProcessingType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessingType.any_instance.stub(:save).and_return(false)
        post :create, {:data_processing_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_processing_type" do
        data_processing_type = DataProcessingType.create! valid_attributes
        # Assuming there are no other data_processing_types in the database, this
        # specifies that the DataProcessingType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataProcessingType.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => data_processing_type.to_param, :data_processing_type => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested data_processing_type as @data_processing_type" do
        data_processing_type = DataProcessingType.create! valid_attributes
        put :update, {:id => data_processing_type.to_param, :data_processing_type => valid_attributes}, valid_session
        assigns(:data_processing_type).should eq(data_processing_type)
      end

      it "redirects to the data_processing_type" do
        data_processing_type = DataProcessingType.create! valid_attributes
        put :update, {:id => data_processing_type.to_param, :data_processing_type => valid_attributes}, valid_session
        response.should redirect_to(data_processing_type)
      end
    end

    describe "with invalid params" do
      it "assigns the data_processing_type as @data_processing_type" do
        data_processing_type = DataProcessingType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessingType.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_processing_type.to_param, :data_processing_type => { "name" => "invalid value" }}, valid_session
        assigns(:data_processing_type).should eq(data_processing_type)
      end

      it "re-renders the 'edit' template" do
        data_processing_type = DataProcessingType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessingType.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_processing_type.to_param, :data_processing_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_processing_type" do
      data_processing_type = DataProcessingType.create! valid_attributes
      expect {
        delete :destroy, {:id => data_processing_type.to_param}, valid_session
      }.to change(DataProcessingType, :count).by(-1)
    end

    it "redirects to the data_processing_types list" do
      data_processing_type = DataProcessingType.create! valid_attributes
      delete :destroy, {:id => data_processing_type.to_param}, valid_session
      response.should redirect_to(data_processing_types_url)
    end
  end

end
