require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataProcessingsController do

  # This should return the minimal set of attributes required to create a valid
  # DataProcessing. As you add validations to DataProcessing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "data_processing_type_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DataProcessingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all data_processings as @data_processings" do
      data_processing = DataProcessing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:data_processings).should eq([data_processing])
    end
  end

  describe "GET show" do
    it "assigns the requested data_processing as @data_processing" do
      data_processing = DataProcessing.create! valid_attributes
      get :show, {:id => data_processing.to_param}, valid_session
      assigns(:data_processing).should eq(data_processing)
    end
  end

  describe "GET new" do
    it "assigns a new data_processing as @data_processing" do
      get :new, {}, valid_session
      assigns(:data_processing).should be_a_new(DataProcessing)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_processing as @data_processing" do
      data_processing = DataProcessing.create! valid_attributes
      get :edit, {:id => data_processing.to_param}, valid_session
      assigns(:data_processing).should eq(data_processing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataProcessing" do
        expect {
          post :create, {:data_processing => valid_attributes}, valid_session
        }.to change(DataProcessing, :count).by(1)
      end

      it "assigns a newly created data_processing as @data_processing" do
        post :create, {:data_processing => valid_attributes}, valid_session
        assigns(:data_processing).should be_a(DataProcessing)
        assigns(:data_processing).should be_persisted
      end

      it "redirects to the created data_processing" do
        post :create, {:data_processing => valid_attributes}, valid_session
        response.should redirect_to(DataProcessing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_processing as @data_processing" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessing.any_instance.stub(:save).and_return(false)
        post :create, {:data_processing => { "data_processing_type_id" => "invalid value" }}, valid_session
        assigns(:data_processing).should be_a_new(DataProcessing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessing.any_instance.stub(:save).and_return(false)
        post :create, {:data_processing => { "data_processing_type_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_processing" do
        data_processing = DataProcessing.create! valid_attributes
        # Assuming there are no other data_processings in the database, this
        # specifies that the DataProcessing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataProcessing.any_instance.should_receive(:update).with({ "data_processing_type_id" => "1" })
        put :update, {:id => data_processing.to_param, :data_processing => { "data_processing_type_id" => "1" }}, valid_session
      end

      it "assigns the requested data_processing as @data_processing" do
        data_processing = DataProcessing.create! valid_attributes
        put :update, {:id => data_processing.to_param, :data_processing => valid_attributes}, valid_session
        assigns(:data_processing).should eq(data_processing)
      end

      it "redirects to the data_processing" do
        data_processing = DataProcessing.create! valid_attributes
        put :update, {:id => data_processing.to_param, :data_processing => valid_attributes}, valid_session
        response.should redirect_to(data_processing)
      end
    end

    describe "with invalid params" do
      it "assigns the data_processing as @data_processing" do
        data_processing = DataProcessing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessing.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_processing.to_param, :data_processing => { "data_processing_type_id" => "invalid value" }}, valid_session
        assigns(:data_processing).should eq(data_processing)
      end

      it "re-renders the 'edit' template" do
        data_processing = DataProcessing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataProcessing.any_instance.stub(:save).and_return(false)
        put :update, {:id => data_processing.to_param, :data_processing => { "data_processing_type_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_processing" do
      data_processing = DataProcessing.create! valid_attributes
      expect {
        delete :destroy, {:id => data_processing.to_param}, valid_session
      }.to change(DataProcessing, :count).by(-1)
    end

    it "redirects to the data_processings list" do
      data_processing = DataProcessing.create! valid_attributes
      delete :destroy, {:id => data_processing.to_param}, valid_session
      response.should redirect_to(data_processings_url)
    end
  end

end
