require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SoftwareParametersController do

  # This should return the minimal set of attributes required to create a valid
  # SoftwareParameter. As you add validations to SoftwareParameter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SoftwareParametersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all software_parameters as @software_parameters" do
      software_parameter = SoftwareParameter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:software_parameters).should eq([software_parameter])
    end
  end

  describe "GET show" do
    it "assigns the requested software_parameter as @software_parameter" do
      software_parameter = SoftwareParameter.create! valid_attributes
      get :show, {:id => software_parameter.to_param}, valid_session
      assigns(:software_parameter).should eq(software_parameter)
    end
  end

  describe "GET new" do
    it "assigns a new software_parameter as @software_parameter" do
      get :new, {}, valid_session
      assigns(:software_parameter).should be_a_new(SoftwareParameter)
    end
  end

  describe "GET edit" do
    it "assigns the requested software_parameter as @software_parameter" do
      software_parameter = SoftwareParameter.create! valid_attributes
      get :edit, {:id => software_parameter.to_param}, valid_session
      assigns(:software_parameter).should eq(software_parameter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SoftwareParameter" do
        expect {
          post :create, {:software_parameter => valid_attributes}, valid_session
        }.to change(SoftwareParameter, :count).by(1)
      end

      it "assigns a newly created software_parameter as @software_parameter" do
        post :create, {:software_parameter => valid_attributes}, valid_session
        assigns(:software_parameter).should be_a(SoftwareParameter)
        assigns(:software_parameter).should be_persisted
      end

      it "redirects to the created software_parameter" do
        post :create, {:software_parameter => valid_attributes}, valid_session
        response.should redirect_to(SoftwareParameter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved software_parameter as @software_parameter" do
        # Trigger the behavior that occurs when invalid params are submitted
        SoftwareParameter.any_instance.stub(:save).and_return(false)
        post :create, {:software_parameter => { "name" => "invalid value" }}, valid_session
        assigns(:software_parameter).should be_a_new(SoftwareParameter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SoftwareParameter.any_instance.stub(:save).and_return(false)
        post :create, {:software_parameter => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested software_parameter" do
        software_parameter = SoftwareParameter.create! valid_attributes
        # Assuming there are no other software_parameters in the database, this
        # specifies that the SoftwareParameter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SoftwareParameter.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => software_parameter.to_param, :software_parameter => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested software_parameter as @software_parameter" do
        software_parameter = SoftwareParameter.create! valid_attributes
        put :update, {:id => software_parameter.to_param, :software_parameter => valid_attributes}, valid_session
        assigns(:software_parameter).should eq(software_parameter)
      end

      it "redirects to the software_parameter" do
        software_parameter = SoftwareParameter.create! valid_attributes
        put :update, {:id => software_parameter.to_param, :software_parameter => valid_attributes}, valid_session
        response.should redirect_to(software_parameter)
      end
    end

    describe "with invalid params" do
      it "assigns the software_parameter as @software_parameter" do
        software_parameter = SoftwareParameter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SoftwareParameter.any_instance.stub(:save).and_return(false)
        put :update, {:id => software_parameter.to_param, :software_parameter => { "name" => "invalid value" }}, valid_session
        assigns(:software_parameter).should eq(software_parameter)
      end

      it "re-renders the 'edit' template" do
        software_parameter = SoftwareParameter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SoftwareParameter.any_instance.stub(:save).and_return(false)
        put :update, {:id => software_parameter.to_param, :software_parameter => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested software_parameter" do
      software_parameter = SoftwareParameter.create! valid_attributes
      expect {
        delete :destroy, {:id => software_parameter.to_param}, valid_session
      }.to change(SoftwareParameter, :count).by(-1)
    end

    it "redirects to the software_parameters list" do
      software_parameter = SoftwareParameter.create! valid_attributes
      delete :destroy, {:id => software_parameter.to_param}, valid_session
      response.should redirect_to(software_parameters_url)
    end
  end

end
